<a href="https://colab.research.google.com/github/LeonVaca/03MAIR---Algoritmos-de-optimizacion---2023/blob/main/Proyecto_Actores_Leon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Algoritmos de optimización - Seminario<br>
IVAN RODRIGO LEON VACA:   <br>
Url:https://github.com/LeonVaca/03MAIR---Algoritmos-de-optimizacion---2023/blob/main/Proyecto_Actores_Leon.ipynb <br>
Problema:
> 1. Sesiones de doblaje <br>



Descripción del problema: Se precisa coordinar el doblaje de una película. Los actores del doblaje deben coincidir en las tomas en las que sus personajes aparecen juntos en las diferentes tomas. Los actores de doblaje cobran todos la misma cantidad por cada dia que deben desplazarse hasta el estudio de 6 tomas por día. El objetivo es planificar las sesiones por día de manera que al gasto por los servicios de los actores de doblaje sea el menor posible. Los datos son:
>Número de actores: 10<br>
>Número de tomas: 30<br>
>Actores y tomas:https://docs.google.com/spreadsheets/d/1Ipn6IrbQP4ax8zOnivdBIw2lN0JISkJG4fXndYd27U0/edit#gid=0 <br>

>-1 indica que el actor participa en la toma<br>
>-0 en caso contrario<br>

(*) La respuesta es obligatoria


In [66]:
import numpy as np

data = np.array([
    [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 1, 0, 1, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 1, 1, 0, 0],
    [0, 1, 0, 1, 0, 0, 0, 1, 0, 0],
    [1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 1, 0, 0, 1, 0],
    [1, 1, 1, 0, 1, 0, 0, 1, 0, 0],
    [1, 1, 1, 1, 0, 1, 0, 0, 0, 0],
    [1, 0, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
    [1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 1, 0, 0, 0, 1, 0],
    [0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 1, 1, 0, 0, 0, 0],
    [1, 0, 0, 1, 0, 0, 0, 0, 0, 0]
])

def greedy(data):
    ntomas, nactores = data.shape
    tomas = [False] * ntomas
    actores = [False] * nactores
    asignacion = [[0 for _ in range(nactores)] for _ in range(ntomas)]
    costo_total = 0

    for dia in range(ntomas // 6):
        tomas_dia = [i for i in range(dia * 6, (dia + 1) * 6)]

        for toma in tomas_dia:
            actores_disponibles = [
                actor for actor in range(nactores) if data[toma][actor] == 1 and not actores[actor]
            ]
            if not actores_disponibles:
                continue

            actor_seleccionado = actores_disponibles[0]
            costo_total += 1
            for t in tomas_dia:
                asignacion[t][actor_seleccionado] = 1
                tomas[t] = True
            actores[actor_seleccionado] = True

    return asignacion, costo_total

asignacion, costo_total = greedy(data)
print("Asignación:")
for i, row in enumerate(asignacion):
    print(f"toma {i+1}: {row}")
print(f"coste total= {costo_total}")


Asignación:
toma 1: [1, 1, 1, 1, 1, 0, 1, 0, 0, 0]
toma 2: [1, 1, 1, 1, 1, 0, 1, 0, 0, 0]
toma 3: [1, 1, 1, 1, 1, 0, 1, 0, 0, 0]
toma 4: [1, 1, 1, 1, 1, 0, 1, 0, 0, 0]
toma 5: [1, 1, 1, 1, 1, 0, 1, 0, 0, 0]
toma 6: [1, 1, 1, 1, 1, 0, 1, 0, 0, 0]
toma 7: [0, 0, 0, 0, 0, 1, 0, 1, 1, 0]
toma 8: [0, 0, 0, 0, 0, 1, 0, 1, 1, 0]
toma 9: [0, 0, 0, 0, 0, 1, 0, 1, 1, 0]
toma 10: [0, 0, 0, 0, 0, 1, 0, 1, 1, 0]
toma 11: [0, 0, 0, 0, 0, 1, 0, 1, 1, 0]
toma 12: [0, 0, 0, 0, 0, 1, 0, 1, 1, 0]
toma 13: [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
toma 14: [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
toma 15: [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
toma 16: [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
toma 17: [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
toma 18: [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
toma 19: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
toma 20: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
toma 21: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
toma 22: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
toma 23: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
toma 24: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
toma 25: [0, 0, 0, 0, 0, 0, 0, 0, 0, 

### (*)¿Cuantas posibilidades hay sin tener en cuenta las restricciones?

In [56]:
import itertools #libreria para generar combinaciones

data = [
    [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 1, 1, 0, 0, 0, 0, 0],

]

def generar_posibilidades(data):
    tomas, actores = len(data), len(data[0])
    posibilidades = []

    for asignacion in itertools.product([0, 1], repeat=tomas * actores):
        asignacion_matriz = [list(asignacion[i:i+actores]) for i in range(0, len(asignacion), actores)]
        posibilidades.append(asignacion_matriz)

    return posibilidades

posibilidades = generar_posibilidades(data)

print(f"posibilidades sin restricciones= {len(posibilidades)}")



posibilidades sin restricciones: 1048576


En el caso de encontrar el numero de posibilidades sin tener en cuenta las restricciones, se multiplica la cantidad de actores por la cantidad de tomas. Para este caso seria: 10x30 = 300
Entonces tenemos 300 posibilidades sin tener en cuenta las restricciones.

Pero por motivos del espacio de RAM no se puede ejecutar el codigo ya que seria un valor de 2^300. Entonces se ejecuto solo 2 filas para el analisis.

### ¿Cuantas posibilidades hay teniendo en cuenta todas las restricciones.

In [64]:
import numpy as np

data = np.array([
    [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 1, 0, 1, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 1, 1, 0, 0],
    [0, 1, 0, 1, 0, 0, 0, 1, 0, 0],
])

actores, tomas = data.shape

def costo_dia(asignar):
    return np.sum(data[:, asignar])

def grasp_asignacion(niteraciones):
    mejor_asignacion = None
    mejor_costo = float('inf')

    for _ in range(niteraciones):
        asignar = [np.random.choice(np.where(data[i] == 1)[0]) for i in range(actores)]
        costo = costo_dia(asignar)

        for _ in range(70):  #iteraciones de busqueda
            for i in range(actores): #mejora busqueda local
                for j in range(tomas):
                    if data[i, j] == 1 and j not in asignar:
                        nueva_asignacion = asignar.copy()
                        nueva_asignacion[i] = j
                        nuevo_costo = costo_dia(nueva_asignacion)

                        if nuevo_costo < costo:
                            asignacion = nueva_asignacion
                            costo = nuevo_costo

        if costo < mejor_costo:
            mejor_asignacion = asignar
            mejor_costo = costo

    return mejor_asignacion, mejor_costo

iteraciones_grasp = 600

asignacion_grasp, costo_grasp = grasp_asignacion(iteraciones_grasp)

print("GRASP:")
print(asignacion_grasp)
print("coste total=", costo_grasp)


GRASP:
[0, 2, 4, 0, 7]
coste total= 10


### Modelo para el espacio de soluciones
### (*) ¿Cual es la estructura de datos que mejor se adapta al problema? Argumentalo.(Es posible que hayas elegido una al principio y veas la necesidad de cambiar, argumentalo)

La estructura de datos que se utiliza para el problema es una matriz binaria, se muestra en la tabla que las filas representan los actores y las columnas representan las tomas. Como se estan almecenando los datos de forma binaria ejemplo 1= si y 0= no. entonces los datos ocupan mucha memoria.
Se debe entender que al momento de acceder a los datos el algoritmo GRASP se ayuda de la matriz binaria para verificar las restricciones y calcular el costo.
Al principio se intento utilizar diagramas y grafos para entender el problema. Pero al momento de ejecucion y llegar a una solucion, se complicaba ya que contiene un coste alto y bastantes restricciones por lo que tiene muchos caminos para encontrar una solucion. Entonces se concluyo que es mucho mas facil trabajar directamente con la matriz binaria.

### Según el modelo para el espacio de soluciones
### (*)¿Cual es la función objetivo?

La función objetivo en este problema es minimizar el coste total de los servicios de los actores. El objetivo es planificar sesiones por día tal que el gasto por los servicios de los actores sea lo menor posible. La funcion objetivo consiste en calcular la suma del numero de tomas en las que cada actor participa. Por lo tanto, para que el coste total sea menor los actores deben de asistir con menor frecuencia al estudio de grabaciones.



### (*)¿Es un problema de maximización o minimización?

El objetivo del problema, es planificar las sesiones por día de manera que el gasto por los servicios de los actores sea lo menor posible. Cuanto menor sea el número de tomas en las que los actores tienen que participar juntos, menor será el costo total, ya que los actores tendrán que asistir con menor frecuencia al estudio de grabaciones. Por lo tanto, el problema es de minimización.

### Diseña un algoritmo para resolver el problema por fuerza bruta

In [62]:
import itertools
import numpy as np

# No es posible con fuerza bruta utilizar todos los datos de la matriz binaria, escogemos solo las primeras 5 filas
data = np.array([
    [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 1, 0, 1, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 1, 1, 0, 0],
    [0, 1, 0, 1, 0, 0, 0, 1, 0, 0],

])

actores, tomas = data.shape

def costo_dia(asignacion):
    return np.sum(data[:, asignacion])

def fuerza_bruta():
    mejor_asignacion = None
    mejor_costo = float('inf')

    for asignacion in itertools.product(range(tomas), repeat=actores):
        if verificar_restricciones(asignacion):
            costo = costo_dia(asignacion)
            if costo < mejor_costo:
                mejor_asignacion = asignacion
                mejor_costo = costo

    return mejor_asignacion, mejor_costo

def verificar_restricciones(asignacion):
    for toma in range(tomas):
        actores_toma = [i for i in range(actores) if asignacion[i] == toma]
        for actor1, actor2 in itertools.combinations(actores_toma, 2):
            if data[actor1, toma] == 1 and data[actor2, toma] == 1:
                return False
    return True

asignacion_bruta, costo_bruta = fuerza_bruta()

print("fuerza bruta:")
print(asignacion_bruta)
print("coste total=", costo_bruta)


fuerza bruta:
(5, 5, 5, 5, 5)
coste total= 0


### Calcula la complejidad del algoritmo por fuerza bruta

O(ntomas ^ nactor) * O(nactor ^ 2) = O(ntomas ^ nactor)

### (*)Diseña un algoritmo que mejore la complejidad del algortimo por fuerza bruta. Argumenta porque crees que mejora el algoritmo por fuerza bruta

In [63]:
import numpy as np

data = np.array([
    [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 1, 0, 1, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 1, 1, 0, 0],
    [0, 1, 0, 1, 0, 0, 0, 1, 0, 0],
])

actores, tomas = data.shape

def costo_dia(asignar):
    return np.sum(data[:, asignar])

def grasp_asignacion(niteraciones):
    mejor_asignacion = None
    mejor_costo = float('inf')

    for _ in range(niteraciones):
        asignar = [np.random.choice(np.where(data[i] == 1)[0]) for i in range(actores)]
        costo = costo_dia(asignar)

        for _ in range(70):  #iteraciones de busqueda
            for i in range(actores): #mejora busqueda local
                for j in range(tomas):
                    if data[i, j] == 1 and j not in asignar:
                        nueva_asignacion = asignar.copy()
                        nueva_asignacion[i] = j
                        nuevo_costo = costo_dia(nueva_asignacion)

                        if nuevo_costo < costo:
                            asignacion = nueva_asignacion
                            costo = nuevo_costo

        if costo < mejor_costo:
            mejor_asignacion = asignar
            mejor_costo = costo

    return mejor_asignacion, mejor_costo

niteraciones_grasp = 600 #iteraciones grasp

asignacion_grasp, costo_grasp = grasp_asignacion(niteraciones_grasp)

print("GRASP:")
print(asignacion_grasp)
print("coste total:", costo_grasp)

GRASP:
[2, 2, 1, 7, 7]
coste total: 10


### (*)Calcula la complejidad del algoritmo

O(ngrasp * nactor * ntomas)

### Según el problema (y tenga sentido), diseña un juego de datos de entrada aleatorios

In [65]:
import numpy as np

def datos_aleatorios(actores, tomas):
    data = np.random.randint(2, size=(actores, tomas)) #matriz aleatoria

    for j in range(tomas): # se verifica que el actor tenga una toma. uno con uno= actor con toma
        if np.sum(data[:, j]) == 0:
            i = np.random.randint(actores)
            data[i, j] = 1

    return data

actores = 10
tomas = 30

datos = datos_aleatorios(actores, tomas) #entrada de datos de forma aleatoria

print("datos de entrada:")
print(datos)


datos de entrada:
[[1 0 0 1 0 0 0 1 1 1 0 0 1 0 0 0 1 1 1 1 0 1 0 1 0 0 1 0 1 0]
 [0 0 0 0 1 1 0 0 1 0 1 0 1 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0]
 [0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1 1 1 1 0 1 0 1 0 1 1 0 1 1]
 [0 1 1 1 0 0 1 0 1 0 1 0 1 1 1 0 1 1 0 1 0 1 1 0 1 0 1 0 0 0]
 [1 1 1 1 0 0 0 1 0 0 0 0 1 0 1 0 0 1 1 0 1 0 1 1 0 0 1 1 0 0]
 [0 1 0 0 0 1 0 1 1 1 0 0 1 0 1 0 1 1 0 0 1 1 1 0 0 1 0 1 1 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 1 1 0 1 1 0 1 0 0 1 1 0 1 1]
 [0 1 1 1 0 0 1 0 0 1 0 1 1 1 1 1 0 0 0 1 0 0 1 1 0 0 0 0 0 1]
 [0 0 1 0 1 1 0 1 1 0 0 1 1 1 0 0 0 0 0 1 0 0 0 0 1 0 1 1 0 1]
 [0 1 0 1 1 1 1 0 1 0 1 0 0 1 1 0 0 0 1 1 0 0 0 0 1 0 1 1 1 1]]


### Describe brevemente las lineas de como crees que es posible avanzar en el estudio del problema. Ten en cuenta incluso posibles variaciones del problema y/o variaciones al alza del tamaño

Se puede utilizar el algoritmo GRASP como se lo utilizo para mejorar la complejidad del problema, GRASP puede mejorar la estrategia de busqueda para ir construyendo soluciones mas optimas.
Como se menciono en clases, existe un metodo heuristico llamado busqueda Tabu, se dice que con este metodo se puede encontrar una mejor solucion al problema ya que es un problema que maneja datos de gran tamaño y tener un mejor espacio de soluciones. Tabu tiene como caracteristicas, establece un mejor proceso de busqueda local, encuentra soluciones vecinas, elige y añade elementos a la nueva lista tabu, establece el tamaño de la lista y establece la regla de detención.
Otro punto importante para el problema es la posibilidad de modificar las restricciones, ejemplo la disponibilidad de los actores en dias que ellos tengan libres, costos de movilidad y desplazamiento.

